spring:
  application:
    name: encurtador
  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:encurtador_db}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:felipe}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: ${PORT:8080}
